services:
  mt4-postgresql-connector:
    image: postgresql_connector-mt4-postgresql-connector
    restart: unless-stopped
    volumes:
      - ./app:/usr/src/mt4-postgresql-connector
    command: uvicorn main:app --reload --port 8000 --host 0.0.0.0
    env_file:
      - .env
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    networks:
      - mt4_network
    depends_on:
      - pgbouncer

  pgbouncer:
    image: edoburu/pgbouncer:latest
    environment:
      - DB_HOST=db
      - DB_USER="${DB_USER}"
      - DB_PASSWORD="${DB_PASSWORD}"
      - DB_DATABASE="${DB_NAME}"
      - LISTEN_PORT="${PGB_LISTEN_PORT}"
      - AUTH_TYPE=plain
      - AUTH_FILE=/pgbouncer/users.txt
    ports:
      - "6432:6432"
    depends_on:
      - db
    volumes:
      - ./pgbouncer/users.txt:/pgbouncer/users.txt
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
    networks:
      - mt4_network
  db:
    container_name: db
    image: postgres
    restart: always
    shm_size: 128mb
    # ports:
    #   - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: kudston
      POSTGRES_DB: postgres
    networks:
      - mt4_network

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    ports:
      - target: 80
        published: 8900
        mode: host

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mt4-postgresql-connector
    networks:
      - mt4_network

networks:
  mt4_network:
    driver: overlay