version: '3.8'

services:
  mt4-postgresql-connector:
    # container_name: mt4-postgresql-connector
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./app:/usr/src/mt4-postgresql-connector
    command: uvicorn main:app --reload --port 8000 --host 0.0.0.0
    env_file:
      - .env
    deploy:
      replicas: 10
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    networks:
      - mt4_network
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: kudston
      POSTGRES_DB: postgres
    networks:
      - mt4_network

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "8900:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mt4-postgresql-connector
    networks:
      - mt4_network

networks:
  mt4_network:
    driver: bridge